### ISSUE TITLE
bug: replace pnpm `workspace:^` correctly

### ISSUE THREAD

**Issue by lyh543** [dhoulb/multi-semantic-release#111]
## Expected behavior

According to [pnpm docs](https://pnpm.io/workspaces#publishing-workspace-packages), `workspace: *` and other versions will be transformed from:

```json
{
    "dependencies": {
        "foo": "workspace:*",
        "bar": "workspace:~",
        "qar": "workspace:^",
        "zoo": "workspace:^1.5.0"
    }
}
```

to:

```json
{
    "dependencies": {
        "foo": "1.5.0",
        "bar": "~1.5.0",
        "qar": "^1.5.0",
        "zoo": "^1.5.0"
    }
}
```

## Current MSR behavior

```json
{
    "dependencies": {
        "foo": "1.5.0",
        "bar": "1.5.0",
        "qar": "1.5.0",
        "zoo": "(not tested)"
    }
}
```

**Comment by lyh543** [comment]
I'm happy to contribute to MSR, however I'm afraid I don't have enough time until July (working on my graduate papers). So I just report this bug right now.

**Comment by antongolub** [comment]
Hey @lyh543,

No rush. Focus on your thesis and come back)

**Comment by lyh543** [comment]
I added code and tests in `resolveNextVersion`, to handle versions like pnpm `workspace:` (see [this commit](https://github.com/lyh543/multi-semantic-release/commit/553e652b0eee0969d8e28318b4ff8cc51724bbe6)).

Now I meet some problems. To be clear, suppose we are talking about a pnpm monorepo including`product`, `foo`, `bar`, `qar` and `zoo`. `product` depends on others, and `product/package.json` looks like this:

```json
{
  "name": "product",
  "version": "1.0.0",
  "dependencies": {
    "foo": "workspace:*",
    "bar": "workspace:^",
    "qar": "workspace:~",
    "zoo": "workspace:^1.1.0",
  },
}
```

After release, `product/package.json` should look like this:

```json
{
  "name": "product",
  "version": "1.0.1",
  "dependencies": {
    "foo": "1.0.0",
    "bar": "^1.0.0",
    "qar": "~1.0.0",
    "zoo": "^1.1.0",
  },
}
```

My release command is: `multi-semantic-release --no-ci --deps.bump satisfy`

------------------------

When we are calling `resolveNextVersion` in  `updateManifestDeps` to determine which version of `foo` will be written to `product/package.json`, we pass in last released version of `foo` (`dependency._lastRelease.version`) as `currentVersion`, not the version defined in `product/package.json`.

https://github.com/dhoulb/multi-semantic-release/blob/2dedffc0bae8380fff8404ef5acd84b20f40f0c3/lib/updateDeps.js#L308-L313

At this point, I think it may be difficult to impement the feature, without passing new params to `resolveNextVersion`, since I can't get `foo`'s version defined in `product/package.json`.

Can anyone help me? Any discussion and help will be appreciated❤
