### ISSUE TITLE
Error: git fetch --tags --update-head-ok

### ISSUE THREAD

**Issue by giuvincenzi** [dhoulb/multi-semantic-release#116]
Sometimes the release process fails with this error:

```
An error occurred while running semantic-release: Error: Command failed with exit code 1: git fetch --tags --update-head-ok [https://gitlab-ci-token:[secure]@gitlab.com/xxx/xxx/npm-packages.git](https://gitlab-ci-token:%5Bsecure%5D@gitlab.com/xxx/xxx/npm-packages.git) +refs/heads/master:refs/heads/master
error: cannot lock ref 'refs/heads/master': is at 4a2316cceb39c1c3c125cda96d95ba7ffbc5b6a0 but expected 60e6a30decd3acbf6ca6c9d5fe408f3ddf4f06e4
```

If I re-run the pipeline job **the second time it always gets done correctly**.

This is the error log:
![bug_git_fetch](https://user-images.githubusercontent.com/14005575/171002981-c7f85241-711b-4829-85a9-1b77f02e6775.png)

I saw that there is an [issue](https://github.com/semantic-release/semantic-release/issues/1545) on the semantic-release repository.

> The issues were resolved by hot patching execa() to execa.sync()

it says that the problem was solved by calling `execa.sync()` instead of `execa()` but I still get the error.

What the right solution would be to avoid this problem?

I'm using:
- npm 8.6 
- node 18 
- multi-semantic-release 2.12.0

**Comment by carvalhoa-ppb** [comment]
Hi guys, I'm having the same issue. 
For me, to have a success run requires a lot of reruns, since I'm allowing releases for more than 1 branch from what I've understood.

Any idea how to bypass it? 🤔

**Comment by giuvincenzi** [comment]
> If I re-run the pipeline job the second time it always gets done correctly.

Now it is always locked, there is no way to make it work.

**Comment by gasparecoolshop** [comment]
Hi all,
I have the same problem with version 3 too, any idea how to resolve this issue?
It's becoming really frustrating to run a pipeline.

**Comment by alboo89** [comment]
Hi everybody, 
same problem and same frustration on every pipeline run. 
@antongolub can you help us please?

**Comment by giuvincenzi** [comment]
The problem is not semantic-release or multi semantic-release but the machine where the script runs.

I run the script on a Gitlab runner and I fixed it running the releases job with "git clone strategy" instead of "git fech strategy"
