### ISSUE TITLE
Run script after successful release

### ISSUE THREAD

**Issue by aleclarson** [dhoulb/multi-semantic-release#126]
After this library does its thing, my repository is left with dirty `package.json` files that I'd like to commit automatically. But before doing that, I want to run `pnpm install` to update the lockfile.

I thought maybe I could use [@semantic-release/exec](https://github.com/semantic-release/exec), but as I understand it, that would run my script once per package in my workspace, right?

So I think this library needs to provide a way to run a script after all releases are finished. WDYT?

**Comment by antongolub** [comment]
Hmm... But why is `semantic release --opts ... && custom script` not suitable for yor case?

**Comment by aleclarson** [comment]
That should work as long as `multi-semantic-release` exits with non-zero on failed release!

**Comment by aleclarson** [comment]
Although, you don't get access to release metadata (eg: which packages were released and their versions) if you do it that way.

**Comment by antongolub** [comment]
1) `multi-semantic-release ; node post-release-script.js` should work.
2) you can introduce your own plugin to capture state (success/failure step). 

The plugin can append release meta to some temp file, so that `post-release-script.js` can process it after.
