### ISSUE TITLE
Plugins do not work as expected

### ISSUE THREAD

**Issue by matzeeable** [dhoulb/multi-semantic-release#14]
Hi @dhoulb !

Nice approach for `multi-semantic-release`! I really love to use `semantic-release` but I manage to move my repositories to a multi-package repository so it will not work until https://github.com/semantic-release/semantic-release/issues/193 is fixed.

I just tried your package but I do not get it to work properly... My configuration of a `package.json` looks like this:

```
"release": {
    "generateNotes": [
        [
            "@semantic-release/release-notes-generator",
            {
                "linkCompare": false,
                "linkReferences": false,
                "writerOpts": {
                    "groupBy": false
                }
            }
        ]
    ]
}
```

but the passed options are ignored and `#23` gets still resolved to a github link which I like to disable.

And is the new scheme for plugins usable (e. g. `plugins: []` instead of `publish: []`)?

Thanks for your answer!

**Comment by dhoulb** [comment]
Hi Matthias

Sorry, I'm not sure why that wouldn't be working! The configuration should be picked up and passed into Semantic Release exactly as provided. 

Unless it's being overridden by the configuration in a sub-package (e.g. a `release.generateNotes` key exists in `packages/a/package.json,` which would override that key in `package.json`)

I haven't looked at Semantic Release's core code in a while though, it's possible they've changed some things that would break this module. I wrote this code a year ago and knew it wasn't strong enough to last forever — but had hoped Semantic Release would have native support for monorepos by now! 

Thanks
Dave
