### ISSUE TITLE
Coordination

### ISSUE THREAD

**Issue by rharkor** [dhoulb/multi-semantic-release#152]
Hi, 

In my monorepos I have two sub package and I want them to be coodinated on their versionning, unfortunately this is not the case see the example below:
![image](https://github.com/dhoulb/multi-semantic-release/assets/70844594/cb0d69e1-087d-4c5f-97ca-042289f8edb0)

Can anyone help me with this ?

Thank you

**Comment by rharkor** [comment]
Also why it always make a new release like 1.1.0-rec.17 => 1.1.0-rec.18 instead of changing the semver version ?

**Comment by antongolub** [comment]
I'm afraid, msr is aimed at the opposite: avoid versions lock to reflect real changes in each package.
It seems that https://github.com/hongaar/semantic-release-yarn may be more suitable for your case.
