### ISSUE TITLE
MSR does not detect Merge Request conventional commit messages

### ISSUE THREAD

**Issue by musaabal-okaidi** [dhoulb/multi-semantic-release#20]
Hi

When adding conventional commit messages to a merge request commits, the multi-semantic-release does not seem to detect these commit so it doesn't bump the version nor does it write a changelog.

Is this an expected behaviour or am I doing something wrong?

Please let me know if you require more elaboration.

**Comment by antongolub** [comment]
Hi, @musaabal-okaidi

Does this issue look like your case? https://github.com/semantic-release/commit-analyzer/issues/65

**Comment by musaabal-okaidi** [comment]
Hi @dhoulb 

Not quite.

I'm writing commit messages that are compliant with the conventional commits guidelines, and these messages are correctly parsed and included in the changelog when I run `semantic-release`

However; my repo is a monorepo, hence I'm using `multi-semantic-release` and when using `multi-semantic-release` those merge commits are detected as changes to my monorepo packages.

Would you like an example repo to demonstrate this or does that make sense?

**Comment by antongolub** [comment]
Reproduced: [builds#175591927](https://travis-ci.com/github/antongolub/release-testing/builds/175591927)
We'll try to fix it.

**Comment by antongolub** [comment]
@musaabal-okaidi, try out the latest build

**Comment by antongolub** [comment]
@musaabal-okaidi, any news?

**Comment by musaabal-okaidi** [comment]
@antongolub I've tested it and it's working as expected. 😃  

Thank you very much for the quick response and fix.

**Comment by musaabal-okaidi** [comment]
Is there a difference between this repo and the forked repo `@qiwi/multi-semantic-release` other than parallel execution?

**Comment by antongolub** [comment]
@musaabal-okaidi, glad to hear that.

`@qiwi/multi-semantic-release` — is just a testing ground for changes required for our in-house development, which may bring unknown side effects. After all the checks, we push this code into the original repository. For example, parallel exec [is now a part](https://github.com/dhoulb/multi-semantic-release/pull/15) of **msr** too. Here's the [discussion about it](https://github.com/qiwi/multi-semantic-release/issues/8).

dhoulb — LTS
qiwi — canary builds

**Comment by musaabal-okaidi** [comment]
Awesome. I'm going to close this issue as it's resolved. If I have other questions or discover anything else then I'll give you a shout.

**Comment by musaabal-okaidi** [comment]
> N.B It's worth noting that we're loosely following a Git Flow approach. So our process is:
> A) Branch off `develop` to work on a new feature. (commit as much as you like without using conventional commit messages)
> B) When the feature is complete, merge to develop using a conventional commit message (to allow that feature to be included i the changelog)
> C) When we're ready for a prod release, we'll merge `develop` to `master` and run tagging/versioning (using `semantic-release`/`multi-semantic-release`

During testing, I've been branching off `master`  then merging straight back into `master` just to save time and that all worked well. 

When I came to do my final test by following the actual process which is branch off `develop` then merge back to `develop` then when we have a set of features ready we'll merge `develop` to `master` I noticed that when I run `multi-semantic-release` on `master` it doesn't pick up the merge commits. Would you be able to resolve this issue as well?
