### ISSUE TITLE
Package.json not formatted when committed

### ISSUE THREAD

**Issue by StevenLangbroek** [dhoulb/multi-semantic-release#22]
I noticed the package.json of the packages we published looks like this after being committed back in by `semantic-release-git`:

![image](https://user-images.githubusercontent.com/296796/87628456-49944480-c731-11ea-9ce0-61134544ed2c.png)

Is this intentional or a bug or misconfiguration or some such?

**Comment by StevenLangbroek** [comment]
Hmmm 🤔 this might also have been borked by something locally. I'll get back on this later this week and confirm or close.

**Comment by antongolub** [comment]
**msr** tries to keep the original `package.json` formatting https://github.com/dhoulb/multi-semantic-release/commit/54d889f32f5bbc75412540bb8c0abb3e4e7d4ec6. Perhaps this part should be improved.

**Comment by antongolub** [comment]
Everything seems to work as it should. If not, feel free to create another one issue.

https://github.com/dhoulb/multi-semantic-release/blob/576688050f6f812a6342e2378c2ac7caa3f13cd4/lib/recognizeFormat.js#L19

https://github.com/dhoulb/multi-semantic-release/blob/576688050f6f812a6342e2378c2ac7caa3f13cd4/lib/updateDeps.js#L152
