### ISSUE TITLE
Preserve trailing newline and don't include unnecessary dependency fields in package.json

### ISSUE THREAD

**Issue by cherryblossom000** [dhoulb/multi-semantic-release#31]
I had a `package.json` like this:

```json
{
  "name": "test",
  "version": "1.1.0",
  "dependencies": {
    "foo": "*"
  },
  "devDependencies": {
    "bar": "*"
  }
}
```

The file had a trailing newline.

After triggering a release, multi-semantic-release converted `package.json` to:

```json
{
  "name": "test",
  "version": "1.1.0",
  "dependencies": {
    "foo": "*"
  },
  "devDependencies": {
    "bar": "*"
  },
  "peerDependencies": {},
  "optionalDependencies": {}
}
```

without a trailing newline.

I know this isn't that important — I could always make a plugin that removes these fields and adds the trailing newline — but it would be nice for multi-semantic-release to preserve trailing newlines and remove empty dependency fields before writing `package.json` because I commit the updated `package.json` using @semantic-release/git.

**Comment by antongolub** [comment]
@cherryblossom000 

It's reasonable and doesn't look complicated. Should we implement this proposal or you'd like to make a pull request?

**Comment by antongolub** [comment]
I suggest to create a separate file and also to move indent resolver into it.

```javascript
recognizeFormat = (content) => {
  const indent = ...
  const eofTrailing = ...

  return {
    indent,
    eofTrailing
  }
}
```

**Comment by cherryblossom000** [comment]
@antongolub I'll work on this.

**Comment by antongolub** [comment]
Great. I'm going to make a small fix: **msr** doesn't seem to update optional dependencies.

**Comment by antongolub** [comment]
@cherryblossom000 

I fixed the manifest patching: now scopes are not added to `package.json` if they were not there initially.
