### ISSUE TITLE
Is it possible to bump all packages with same version?

### ISSUE THREAD

**Issue by nodkz** [dhoulb/multi-semantic-release#4]
@dhoulb can you point me how to setup monorepo with semantic-release where all packages will be published under the same version even changes occur just in one package?

Want to migrate [mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server) on monorepo ([issue](https://github.com/nodkz/mongodb-memory-server/issues/159#issuecomment-474398550)):
- have one core package
- and other packages with just several lines of code which call core with specific options.

No matter where changes was made, I want to bump all packages with the same new version.

Any help will be very appreciated.
Thanks.

**Comment by dhoulb** [comment]
@nodkz That’s not possible with this package.

Why do you want to do that? This package already takes care of versioning etc and keeping the local deps up to date.
