### ISSUE TITLE
Does this analyse non-scoped commits?

### ISSUE THREAD

**Issue by PaulRBerg** [dhoulb/multi-semantic-release#5]
First of all, many thanks for pulling this together, I think it's a great step forward towards building cleverer monorepos.

Question: does this tool analyse commits for their actual file differences, or just checks the scope of each commit? That is, if I modify both package `a` and package `b`, with package `c` depending on both of them, but I do **not** scope my commit because I updated more than one package, will multi-semantic-release figure that out and properly update `c` too?

**Comment by dhoulb** [comment]
Hi Paul

First of all I think it's important to make clear that I don't consider this repo production ready (as noted in the readme), though it does seem to be working well for a number of people.

But yes! It does what you've said. Package `c` in your scenario will receive a version bump (and will released with release notes along the lines of the following).

```md
## Dependencies
- `package-a` was upgraded to `1.2.3`
- `package-b` was upgraded to `4.5.6`
```
