### ISSUE TITLE
new fix ignore private packages :(

### ISSUE THREAD

**Issue by IGZangelcostales** [dhoulb/multi-semantic-release#77]
Hello!! 

My multi-semantic-release stop working since update 2.8.5 (ignore private packages). I need to use private packages to create releases.

now, how can I create releases for private packages? is there any option? Thank you.

**Comment by antongolub** [comment]
@reuzel 

Let's introduce a flag for this behaviour.

**Comment by moroine** [comment]
I can add the option next week. Could you give a bit more context about your usage of private package? I'll be able to look into this next week.

I was assuming semantic release used with npm and private packages are not published there. Did version `2.8.4` was working as expected? Because on my side, I was running with an infinite loop due to private package.

**Comment by IGZangelcostales** [comment]
Thanks for review this. 

I use it for a repository that has like 15 microservices (all in python) I only use Yarn (package.json) for the tag and release of all of those microservices. Because I use Lerna workspaces I need that the packages are defined as privates (if not I get an error: Workspaces can only be enabled in private projects) and if you ignore the private packages I am left in limbo.

Version 2.8.4 is working as expected. Maybe only for my use, I only use private packages.

**Comment by moroine** [comment]
@IGZangelcostales for workspace, that's the root package.json which is required to be private, not the one in packages

**Comment by IGZangelcostales** [comment]
you are right, I have removed the "private" from the rest of the packages, and semantic-release start working with 2.8.5 without problems. Thank you a lot.

**Comment by moroine** [comment]
@IGZangelcostales should we close this issue?

**Comment by cherryblossom000** [comment]
Ignoring private packages should have been considered a breaking change. Private packages are not ignored by `semantic-release`, unlike what #76 says. In fact, [`semantic-release`'s FAQ](https://semantic-release.gitbook.io/semantic-release/support/faq#why-is-the-package-jsons-version-not-updated-in-my-repository) suggests using a private package to update the `version` in `package.json` (e.g. to push via git) without publishing to npm:

> If you wish to only update the `package.json` and push via Git you can set the project to `"private": true`, within your `package.json` to prevent publishing to the npm registry.

This is exactly how I was using private packages with multi-semantic-release.

I like the suggestion of using a flag; I think the default should be set to include private packages, however, as this is what the behaviour was before 2.8.5.
