### ISSUE TITLE
Releasing from GitHub Actions npm ERR!! code ENEEDAUTH

### ISSUE THREAD

**Issue by EricCrosson** [dhoulb/multi-semantic-release#82]
Hi, this is a cool package! I'm really excited to get it working

### What I've done:

- I have 2fa enabled in npm (authorization only)
- I configured an automation npm token via github secrets (as I do with non-multi semantic-release)
- I have a GitHub action invoke `npx multi-semantic-release`, passing the github token and npm token env vars

This is all visible [here](https://github.com/typescript-tools/typescript-tools/blob/beta/.github/workflows/release.yml)

### What I expected to happen:

`multi-semantic-release` is able to publish npm packages to registry.npmjs.org

### What actually happens:

I am consistently getting the same error,

```
npm ERR! code ENEEDAUTH
343
npm ERR! need auth This command requires you to be logged in.
344
npm ERR! need auth You need to authorize this machine using `npm adduser`
```

visible here: https://github.com/typescript-tools/typescript-tools/runs/3975804717?check_suite_focus=true

I've tried every variation of configuration I can imagine over the past day. Do you know what I'm doing wrong / do you have a working example I can compare against?

**Comment by EricCrosson** [comment]
I was able to deploy locally! 

```
[6:56:59 PM] › 🎉  Released 5 of 24 packages, semantically!
```

I had to comment out these three lines in my local copy of @semantic-version/npm: https://github.com/semantic-release/npm/blob/master/index.js#L42-L44

As a result, I'm going to consider this a bug with @semantic-release/npm and open an issue there instead. I hope to update here when I have a successful resolution.

Again, thank you so much for your help @antongolub. You really went above and beyond to help me get a working setup.

**Comment by antongolub** [comment]
@EricCrosson,

Yet another temporary workaround: https://github.com/semrel-extra/npm

**Comment by EricCrosson** [comment]
Beautiful!

**Comment by patrickarlt** [comment]
I was running into a similar issue but getting a `EINVALIDNPMTOKEN` error even after setting up a valid token and ensuring all the settings were correct in NPM.

```
[7:23:27 PM] [@esri/arcgis-rest-developer-credentials] › ✖  EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry [https://registry.npmjs.org/.](https://registry.npmjs.org/)

If you are using Two Factor Authentication for your account, set its level to "Authorization only" (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) in your account settings. semantic-release cannot publish with the default "
Authorization and writes" level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.

[multi-semantic-release]: AggregateError: 
    SemanticReleaseError: Invalid npm token.
```

But the code in https://github.com/dhoulb/multi-semantic-release/issues/82#issuecomment-950139007 solved it for me so I'm hoping the helps someone else eventually.

<img width="553" alt="2024-06-01_09-37-17" src="https://github.com/dhoulb/multi-semantic-release/assets/378557/20289197-d155-4700-9418-f89f72250b1c">
