### ISSUE TITLE
Is dependent versioning available?

### ISSUE THREAD

**Issue by cesalberca** [dhoulb/multi-semantic-release#93]
I want all my packages to be dependent, meaning that if I make a breaking change in a package all my other packages' versions are bumped to the same version. Is this possible with this library?

**Comment by antongolub** [comment]
Hey, @cesalberca,

Technically yes, it seems possible right now under certain conditions:

1) All the packages have the same major version.
2) The packages form a graph with a single source entry: there is only one package that all the others depend on along the chain (for example, `@scope/common`).
3) Release should be run with opts: `--deps.release='inherit'`, `--deps.bump='override'`.

But this is, of course, a workaround.

**Comment by cesalberca** [comment]
Thanks for your answer, although in this case and after debating it with the team we are actually moving to independent versions in some cases it might be nice to have the option to have dependent versions under a flag.
